// ontario_locations.js

var ontarioLocations = [
"Toronto",
"Ottawa",
"Mississauga",
"Brampton",
"Hamilton",
"London",
"Markham",
"Vaughan",
"Kitchener",
"Windsor",
"Richmond Hill",
"Oakville",
"Burlington",
"Greater Sudbury",
"Oshawa",
"Barrie",
"St. Catharines",
"Cambridge",
"Kingston",
"Whitby",
"Guelph",
"Thunder Bay",
"Waterloo",
"Brantford",
"Pickering",
"Niagara Falls",
"Ajax",
"Chatham-Kent",
"Milton",
"Newmarket",
"Peterborough",
"Sarnia",
"Sault Ste. Marie",
"Kawartha Lakes",
"Sudbury",
"Belleville",
"Woodstock",
"Cornwall",
"North Bay",
"Timmins",
"Quinte West",
"St. Thomas",
"Stratford",
"Orillia",
"Orangeville",
"Brockville",
"Owen Sound",
"Thorold",
"Pembroke",
"Kenora",
"Port Colborne",
"Huntsville",
"Midland",
"Elliot Lake",
"Collingwood",
"Tillsonburg",
"Temiskaming Shores",
"Port Hope",
"Gravenhurst",
"St. Marys",
"Arnprior",
"Parry Sound",
"Bancroft",
"Smiths Falls",
"Haliburton",
"Espanola",
"Cochrane",
"Hearst",
"Kapuskasing",
"Blind River",
"Smooth Rock Falls",
"Marathon",
"Rainy River",
"Englehart",
"Red Lake",
"Atikokan",
"Mattawa",
"New Liskeard",
"Sioux Lookout",
"Moosonee",
"Fort Frances",
"Ignace",
"Sturgeon Falls",
"Hornepayne",
"Deseronto",
"Kirkland Lake",
"Latchford",
"Sioux Lookout",
"Spanish",
"Armstrong",
"Manitouwadge",
"Terrace Bay",
"Schreiber",
"Kenora",
"Dryden",
"Rainy River",
"Cornwall",
"Wawa",
"Cochrane",
"Schreiber",
"Ignace",
"Smooth Rock Falls",
"Kapuskasing",
"Hornepayne",
"Sioux Lookout",
"Atikokan",
"Mattawa",
"Rainy River",
"Fort Frances",
"Moosonee",
"Red Lake",
"New Liskeard",
"Englehart",
"Deseronto",
"Terrace Bay",
"Ajax",
"Amherstburg",
"Aurora",
"Bracebridge",
"Bradford West Gwillimbury",
"Caledon",
"Carleton Place",
"Cobourg",
"Collingwood",
"East Gwillimbury",
"Essex",
"Fort Erie",
"Grimsby",
"Halton Hills",
"Huntsville",
"Innisfil",
"Kingsville",
"Lincoln",
"Midland",
"Milton",
"Mono",
"New Tecumseth",
"Niagara-on-the-Lake",
"Orangeville",
"Pelham",
"Penetanguishene",
"Perth",
"Petawawa",
"Plympton-Wyoming",
"Port Hope",
"Prescott",
"Richmond Hill",
"Saugeen Shores",
"South Bruce Peninsula",
"St. Marys",
"Tecumseh",
"The Blue Mountains",
"Wasaga Beach",
"Whitchurch-Stouffville",
"Bracebridge",
"Collingwood",
"Hanover",
"Hawkesbury",
"Ingersoll",
"LaSalle",
"Midland",
"New Tecumseth",
"Orangeville",
"Pelham",
"Penetanguishene",
"Perth",
"Plympton-Wyoming",
"Port Hope",
"Prescott",
"Richmond Hill",
"Saugeen Shores",
"Smiths Falls",
"South Bruce Peninsula",
"St. Marys",
"Tecumseh",
"The Blue Mountains",
"Wasaga Beach",
"Whitchurch-Stouffville",
"Bracebridge",
"Collingwood",
"Deep River",
"Essex",
"Fort Erie",
"Gananoque",
"Greater Napanee",
"Grimsby",
"Halton Hills",
"Hanover",
"Hawkesbury",
"Ingersoll",
"Innisfil",
"Kingsville",
"LaSalle",
"Lakeshore",
"Leamington",
"Lincoln",
"Minto",
"New Tecumseth",
"Niagara-on-the-Lake",
"Orangeville",
"Pelham",
"Penetanguishene",
"Perth",
"Petawawa",
"Plympton-Wyoming",
"Port Hope",
"Prescott",
"Richmond Hill",
"Saugeen Shores",
"Smiths Falls",
"South Bruce Peninsula",
"St. Marys",
"Tecumseh",
"The Blue Mountains",
"Wasaga Beach",
"Whitchurch-Stouffville",
"Bracebridge",
"Collingwood",
"Deep River",
"Essex",
"Fort Erie",
"Gananoque",
"Greater Napanee",
"Grimsby",
"Halton Hills",
"Hanover",
"Hawkesbury",
"Ingersoll",
"Innisfil",
"Kingsville",
"LaSalle",
"Lakeshore",
"Leamington",
"Lincoln",
"Minto",
"New Tecumseth",
"Niagara-on-the-Lake",
"Orangeville",
"Pelham",
"Penetanguishene",
"Perth",
"Petawawa",
"Plympton-Wyoming",
"Port Hope",
"Prescott",
"Richmond Hill",
"Saugeen Shores",
"Smiths Falls",
"South Bruce Peninsula",
"St. Marys",
"Tecumseh",
"The Blue Mountains",
"Wasaga Beach",
"Whitchurch-Stouffville",
"Bracebridge",
"Collingwood",
"Deep River",
"Essex",
"Fort Erie",
"Gananoque",
"Greater Napanee",
"Grimsby",
"Halton Hills",
"Hanover",
"Hawkesbury",
"Ingersoll",
"Innisfil",
"Kingsville",
"LaSalle",
"Lakeshore",
"Leamington",
"Lincoln",
"Minto",
"New Tecumseth",
"Niagara-on-the-Lake",
"Orangeville",
"Pelham",
"Penetanguishene",
"Perth",
"Petawawa",
"Plympton-Wyoming",
"Port Hope",
"Prescott",
"Richmond Hill",
"Saugeen Shores",
"Smiths Falls",
"South Bruce Peninsula",
"St. Marys",
"Tecumseh",
"The Blue Mountains",
"Wasaga Beach",
"Whitchurch-Stouffville",
"Bracebridge",
"Collingwood",
"Deep River",
"Essex",
"Fort Erie",
"Gananoque",
"Greater Napanee",
"Grimsby",
"Halton Hills",
"Hanover",
"Hawkesbury",
"Ingersoll",
"Innisfil",
"Kingsville",
"LaSalle",
"Lakeshore",
"Leamington",
"Lincoln",
"Minto",
"New Tecumseth",
"Niagara-on-the-Lake",
"Orangeville",
"Pelham",
"Penetanguishene",
"Perth",
"Petawawa",
"Plympton-Wyoming",
"Adelaide Metcalfe",
"Alfred and Plantagenet",
"Alnwick/Haldimand",
"Amaranth",
"Asphodel-Norwood",
"Athens",
"Augusta",
"Baldwin",
"Blandford-Blenheim",
"Bonnechere Valley",
"Brant",
"Brudenell, Lyndoch and Raglan",
"Cavan Monaghan",
"Central Elgin",
"Central Frontenac",
"Central Huron",
"Central Manitoulin",
"Champlain",
"Chatsworth",
"Clarence-Rockland",
"Clarington",
"Clearview",
"Dysart et al",
"Elizabethtown-Kitley",
"Essa",
"Front of Yonge",
"Frontenac Islands",
"Georgian Bay",
"Georgian Bluffs",
"Gravenhurst",
"Greater Madawaska",
"Grey Highlands",
"Haldimand",
"Hamilton",
"Hastings Highlands",
"Havelock-Belmont-Methuen",
"Highlands East",
"Howick",
"Huron East",
"Joly",
"Killaloe, Hagarty and Richards",
"Lanark Highlands",
"Laurentian Hills",
"Loyalist",
"Madawaska Valley",
"Magnetawan",
"Marmora and Lake",
"McNab/Braeside",
"Merrickville-Wolford",
"Minden Hills",
"North Algona Wilberforce",
"North Dundas",
"North Frontenac",
"North Glengarry",
"North Kawartha",
"North Stormont",
"Northeastern Manitoulin and the Islands",
"Oliver Paipoonge",
"Puslinch",
"South Bruce Peninsula",
"South Dundas",
];
